stages:
  - build
  - docker
  - deploy

variables:
  APP_NAME: msa-psa-employee-ui


build:
  stage: build
  image: $DOCKER_REGISTRY_PROXY/node:12-alpine
  cache:
    paths:
      - node_modules/
      - .next/
  variables:
    NODE_ENV: development
  script:
    - unset CI
    - npm i
    - npm run build
  artifacts:
    paths:
      - build
    expire_in: 1 day

docker:
  stage: docker
  image: $DOCKER_REGISTRY_PROXY/docker:dind
  before_script:
    - until docker info; do sleep 1; done
  script:
    - docker build . -t $APP_NAME --build-arg DOCKER_REGISTRY_PROXY=$DOCKER_REGISTRY_PROXY
    - docker tag $APP_NAME $DOCKER_REGISTRY/psa/$APP_NAME:latest
    - docker tag $APP_NAME $DOCKER_REGISTRY/psa/$APP_NAME:$CI_COMMIT_REF_SLUG
    - docker tag $APP_NAME $DOCKER_REGISTRY/psa/$APP_NAME:sha$CI_COMMIT_SHORT_SHA
    - docker login $DOCKER_REGISTRY --username gitlab --password $DOCKER_REGISTRY_PASSWORD
    - docker push --all-tags $DOCKER_REGISTRY/psa/$APP_NAME
  dependencies:
    - build

.deploy:
  variables:
    GIT_STRATEGY: none
  image: $DOCKER_REGISTRY_PROXY/bitnami/kubectl:latest
  script:
    - kubectl -n $NAMESPACE set image deployments/$APP_NAME $APP_NAME=$DOCKER_REGISTRY/psa/$APP_NAME:sha$CI_COMMIT_SHORT_SHA
  rules:
    - when: manual

deploy dev1:
  stage: deploy
  extends:
    - .deploy
  variables:
    NAMESPACE: psa
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop'
      when: on_success
    - when: manual

deploy dev2:
  stage: deploy
  extends:
    - .deploy
  variables:
    NAMESPACE: psa-dev2
  rules:
    - when: manual

deploy dev3:
  stage: deploy
  extends:
    - .deploy
  variables:
    NAMESPACE: psa-dev3
  rules:
    - when: manual

deploy dev4:
  stage: deploy
  extends:
    - .deploy
  variables:
    NAMESPACE: psa-dev4
  rules:
    - when: manual


deploy prod:
  stage: deploy
  variables:
    GIT_STRATEGY: none
    TAG: sha$CI_COMMIT_SHORT_SHA
    GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/id_rsa
  image: $DOCKER_REGISTRY_PROXY/argocd-deployer-image:v4
  before_script:
    - echo $GITLAB_ID_RSA | base64 -d > /tmp/id_rsa
    - chmod 400 /tmp/id_rsa
    - argocd login "$ARGOCD_SERVER" --username="$ARGOCD_USERNAME" --password="$ARGOCD_PASSWORD"
  script:
    - git clone git@neogit.neoflex.ru:neo-projects/iac/helm-infra.git
    - cd helm-infra/cluster
    - yq -yi ".images.employeeui|=\"${TAG}\"" values.yaml
    - git add values.yaml
    - git commit -m "Bump Login UI version to ${TAG}"
    - git push
    - argocd app sync cluster --revision HEAD --force --grpc-web
    - argocd app wait cluster --health --grpc-web
    - argocd app sync prod --revision HEAD --force --grpc-web
    - argocd app wait prod --health --grpc-web
    - argocd app sync prod-psa-env-chart --revision HEAD --force --grpc-web
    - argocd app wait prod-psa-env-chart --health --grpc-web
    - argocd app sync msa-psa-employee-ui-prod --revision HEAD --force --grpc-web
    - argocd app wait msa-psa-employee-ui-prod --health --grpc-web
  environment: prod
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: on_success
    - when: manual
