export default {
    APP_SET_LOADING: 'APP_SET_LOADING',
    APP_SET_ERROR: 'APP_SET_ERROR',

    APP_SET_POSITIONS: 'APP_SET_POSITIONS',
    APP_SET_BUSINESS_ENTITIES: 'APP_SET_BUSINESS_ENTITIES',
    APP_SET_LOCATIONS: 'APP_SET_LOCATIONS',
    APP_SET_COMPANY_ROLES: 'APP_SET_COMPANY_ROLES',
    APP_SET_EMPLOYEE_GROUPS: 'APP_SET_EMPLOYEE_GROUPS',
    APP_SET_EMPLOYEE_DEPARTMENTS: 'APP_SET_EMPLOYEE_DEPARTMENTS',
    APP_SET_PROJECT_STATUSES: 'APP_SET_PROJECT_STATUSES',
    APP_SET_SPECIALIZATIONS: 'APP_SET_SPECIALIZATIONS',

    AUTH_SET_LOADING: 'AUTH_SET_LOADING',
    AUTH_SET_ERROR: 'AUTH_SET_ERROR',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',

    EMPLOYEE_SET_LIST: 'EMPLOYEE_SET_LIST',

    PROFILE_SET_DATA: 'PROFILE_SET_DATA',

    CAREER_HISTORY_SET: 'CAREER_HISTORY_SET',

    PROFILE_SET_PROJECT_ASSIGNMENTS: 'PROFILE_SET_PROJECT_ASSIGNMENTS',
};
